# Generated by Django 4.1.3 on 2022-11-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
