# Generated by Django 4.1.3 on 2022-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membership', '0003_person_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('member', 'Member'), ('librarian', 'Librarian')], default='member', max_length=11),
        ),
    ]
